#include "node-redirect.h"

namespace spg::gopher
{

    NodeRedirect::NodeRedirect(
            const settings::Settings& sets,
            const std::string& h) :
        Node(
            NodeType::NT_HYPERTEXT,
            h.c_str() + 4,  // 4 = length("URL:")
            h,
            sets.host_name,
            sets.listen_port
        ),
        settings(sets),
        href(h)
    {
    }

    std::unique_ptr<proto::Writer> NodeRedirect::make_writer(
            const WriteParams& wp,
            const request::Request& req)
    {
        proto::BytesWriter* writer = new proto::BytesWriter(wp);
        std::unique_ptr<Writer> out(writer);

        // TODO: have these in a conf.h with autotools
#define SERVER "spg"
#define VERSION "0.0"

        std::string text(
            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">"
            "<html>"
            "<head>"
            "<meta http-equiv=\"refresh\" content=\"5;URL=${URL}/\">"
            "<title>Redirection to URL: ${URL}"
            "</head>"
            "<body>"
            "<p>"
            "You are following a link from gopher to another URL or protocol. You"
            "will be automatically taken to the site shortly.  If you don't get"
            "sent there, please click <a href=\"${URL}\">here</a> to go to the site."
            "</p>"
            "<p>"
            "The URL linked is:"
            "</p>"
            "<p>"
            "<a href=\"${URL}\">${URL}</a>"
            "</p>"
            "<hr>"
            "<address>generated by " SERVER " " VERSION "</address>"
            "</body>"
            "</html>"
        );
        writer->append(text);

        return out;
    }


}
